version: '2'


services:

    django:
        build:
            context: .
            dockerfile: Dockerfile

        env_file: env

        ports:
            - "5000:5000"
        depends_on:
            - postgres
            - redis

    redis:
        image: redis

    postgres:
        image: postgres
        volumes:
            - pg_data:/var/lib/postgresql

volumes:
    pg_data: {}
