version: '2'


services:

    django:
        build:
            context: .
            dockerfile: Dockerfile

        command: /start-server.sh
        env_file: envs
        volumes:
            - "./src:/app"

        ports:
            - "5000:5000"
            - "8000:8000"
        depends_on:
            - postgres
            - redis

    redis:
        image: redis

    postgres:
        image: postgres
        volumes:
            - pg_data:/var/lib/postgresql

volumes:
    pg_data: {}
